/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    extend: {},
    padding: {
      50: "50%",
      24: "6rem",
    },
  },
  safelist: [
    // Layout & Flexbox
    "h-screen",
    "w-60",
    "h-60",
    "overflow-hidden",
    "relative",
    "flex",
    "flex-row",
    "float-right",
    "items-center",
    "w-50%",
    "float-left",
    "container",
    "sm:container",
    "mx-auto",
    "justify-between",
    "justify-center",
    "items-stretch",
    "w-full",
    "h-full",
    "flex-1",
    "w-1/4",
    "sm:w-1/3",
    "sm:w-auto",
    "inline-flex",
    "h-4/6",
    "basis-1/2",
    "basis-1/3",
    "basis-2/3",
    "basis-2/4",
    "basis-3/4",
    "basis-1/4",

    // Spacing & Padding
    "pb-0",
    "p-1",
    "p-1.5",
    "pt-1.5",
    "p-2",
    "pt-2",
    "py-2",
    "p-2.5",
    "py-2.5",
    "px-2.5",
    "pb-3",
    "py-3",
    "px-3",
    "px-3.5",
    "p-4",
    "pt-4",
    "py-4",
    "px-4",
    "px-6",
    "py-1.5",
    "pl-50",
    "pr-50",
    "mb-1.5",
    "pr-24",
    "pl-24",
    "sm:p-6",

    // Typography
    "text-left",
    "text-sm",
    "text-lg",
    "text-xs",
    "text-base",
    "font-light",
    "font-normal",
    "font-medium",

    // Colors & Backgrounds
    "text-primary-500",
    "text-gray-500",
    "dark:text-gray-400",
    "dark:text-slate-400",
    "text-gray-900",
    "text-white",
    "bg-neutral-300",
    "opacity-50",
    "bg-white-500",
    "dark:bg-neutral-800",
    "dark:bg-white-300",
    "dark:bg-slate-800",
    "dark:hover:bg-gray-800/50",

    // Borders & Rings
    "rounded-3xl",
    "rounded-full",
    "rounded-lg",
    "rounded-md",
    "ring-1",
    "ring-gray-200",
    "dark:ring-gray-200",
    "ring-primary-500",
    "dark:ring-gray-700",

    // Transitions & Animations
    "transition",
    "ease-in-out",
    "duration-150",
    "transition-transform",
    "duration-200",
    "transition-[height]",
    "ease-out",
    "animate-spin",
    "focus:outline-none",
    "focus:ring-2",

    // Shadows
    "shadow",
    "shadow-md",

    // Icons & Misc
    "ms-auto",
    "transform",
    "overflow-hidden",
    "w-40",
    "break-all",
    "line-clamp-1",
    "rotate-90",

    // Variants
    "hover:text-gray-700",
    "hover:underline",
    "hover:bg-gray-50",
    "dark:hover:text-gray-200",
    "focus-visible:ring-inset",
    "focus-visible:ring-2",
    "focus-visible:ring-black-500",
    "dark:focus-visible:ring-primary-400",

    // Utility classes
    "disabled:cursor-not-allowed",
    "disabled:opacity-75",
    "aria-disabled:cursor-not-allowed",
    "aria-disabled:opacity-75",
    "focus-visible:outline",
    "focus-visible:outline-2",
    "focus-visible:outline-offset-2",

    // Gaps & Sizes
    "gap-x-2.5",
    "gap-x-2",
    "gap-x-1.5",
    "gap-x-1",
    "h-5",
    "w-5",
    "h-6",
    "w-6",
    "h-4",
    "w-4",

    // Button Variants
    "text-{color}-500",
    "dark:text-{color}-400",
    "bg-{color}-50",
    "hover:bg-{color}-100",
    "dark:hover:bg-{color}-900",
    "focus-visible:ring-{color}-500",
    "dark:focus-visible:ring-{color}-400",
    "ring-1",
    "ring-inset",
    "ring-current",

    // Default Settings
    "truncate",
    "w-100",
  ],
};
